apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-onlineproduct-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: onlineproduct
        image: jonathanputra23/docker-onlineproduct
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: onlineproduct-service
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 31000
